Repository COS301-SE-2024/GDPR-data-noncompliance-detector, pull requests merged in 2024-08, with the labels that each got.

#171 Do not touch(frontend final)
  gnd-app/src/app/inbox/inbox.component.css
  gnd-app/src/app/inbox/inbox.component.html
  gnd-app/src/app/inbox/inbox.component.ts
  gnd-app/src/app/upload-document/upload-document.component.html
Labels: frontend, integration, report generation

#185 Feature/report gen
  .gitignore
  backend/Detection_Engine/GND_LSG.jpg
  backend/Detection_Engine/Mediator Narrow Web Extra Bold.ttf
  backend/Detection_Engine/__init__.py
  backend/Detection_Engine/biometric_detection.py
  backend/Detection_Engine/circle-question-regular.jpg
  backend/Detection_Engine/detection_engine.py
  backend/Detection_Engine/location-dot-solid.jpg
  backend/Detection_Engine/report_generation_layer.py
  backend/File_monitor/file_watcher.py
  backend/File_monitor/file_watcher_path.py
  backend/Generated_Reports/violation_report_20240811_152635.pdf
  backend/Generated_Reports/violation_report_20240811_154057.pdf
  backend/Reports/NCE1_report.txt
  backend/Reports/NCEX1_report.txt
  backend/Reports/_report.txt
  backend/backend_entry.py
  backend/backend_entry_int_test.py
  backend/flask_api.py
  gnd-app/main.js
  gnd-app/package-lock.json
  gnd-app/package.json
  gnd-app/src/app/app.component.html
  gnd-app/src/app/inbox/inbox.component.css
  gnd-app/src/app/inbox/inbox.component.html
  gnd-app/src/app/inbox/inbox.component.ts
  gnd-app/src/app/services/report-gen.service.spec.ts
  gnd-app/src/app/services/report-gen.service.ts
  gnd-app/src/app/upload-document/upload-document.component.css
  gnd-app/src/app/upload-document/upload-document.component.html
  gnd-app/src/app/upload-document/upload-document.component.spec.ts
  gnd-app/src/app/upload-document/upload-document.component.ts
  gnd-app/src/assets/logo.ico
  gnd-app/src/assets/logo.png
  gnd-app/src/logo.ico
  gnd-app/tailwind.config.js
  requirements.txt
Labels: Document Parser, frontend, integration, report generation, API

#186 Feature/report gen
  backend/Detection_Engine/biometric_detection.py
  backend/Detection_Engine/report_generation_layer.py
  backend/Reports/NCEWD1_report.txt
  backend/Reports/NCEX1_report.txt
  backend/Reports/dutch.txt
  backend/Reports/twoBirds_report.txt
  backend/backend_entry.py
  gnd-app/src/app/home/home.component.ts
  gnd-app/src/app/upload-document/upload-document.component.html
  gnd-app/src/app/upload-document/upload-document.component.spec.ts
Labels: frontend
